# This file was generated by GoReleaser. DO NOT EDIT.
cask "carl" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "c86217621e283173809e33e32093f59229357903f5c22160258846733c835e00"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c0ac7ad20533fe1fe3a8551dc8e0ce99cb131c919977fa1576c50d5b886ae99"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc1757f6647a5622114f674292ae945ce4f4c01428f93f4e65324d44c1cecc65"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a77dcfaae9195f6f5974b365835fd4b2af6920ddca5e0b6f0c0f0d4666863f3"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "carl"
  desc "cARL — Cognitive Agent Runtime Layer for AI coding agents"
  homepage "https://github.com/goldjg/cARL"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carl"

  # No zap stanza required

end
