# This file was generated by GoReleaser. DO NOT EDIT.
cask "carl" do
  version "1.0.0-rc.1"

  on_macos do
    on_intel do
      sha256 "8ad4d124acbd1599e4f36b62e10cb310efd658fffe164aa011d9c3d1791bfd3e"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b1bf340fd3a0917ef4062c8568fc3b44293e842820893f93c3137b53f3225f35"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "64a499badeaece699c89f02cf3aeda0091d4028bc937a652dcb89a4f433e816b"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6145c42a1c03e12a954539bbf6bfbbf763f3bf48666b981b02971452ba53ea58"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "carl"
  desc "cARL — Cognitive Agent Runtime Layer for AI coding agents"
  homepage "https://github.com/goldjg/cARL"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carl"

  # No zap stanza required

end
