# This file was generated by GoReleaser. DO NOT EDIT.
cask "carl" do
  version "0.4.2"

  on_macos do
    on_intel do
      sha256 "19018f92219beca153043ea0cb865e23dfb46a5fb3e70529e6439e991c9fa41f"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "525401b71f3771101af9b6837e1f6325b1101962995a9553fc40ecc042930ad5"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2aa15f49ee44a63a467d0d39dcf725e69d7cad914cd92f262b94ccf06c0f0629"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9e5a553b616280e89496a5b8a81cbe21603b24dc933b6822bb0b6df59fece18"
      url "https://github.com/goldjg/cARL/releases/download/v#{version}/carl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "carl"
  desc "cARL — Cognitive Agent Runtime Layer for AI coding agents"
  homepage "https://github.com/goldjg/cARL"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "carl"

  # No zap stanza required

end
